INSERT INTO AUTH_SCHEMA."USER" (ID, NAME, LOGIN, PASSWORD, IS_BLOCKED, CREATED_AT, UPDATED_AT, IS_PASS_EXPIRED, PASS_EXPIRE_DATE, IS_ENABLE) VALUES(AUTH_SCHEMA.SEQ_USER.NEXTVAL, 'ANDERSON DIAS', 'andersoninfonet@gmail.com', '$2a$12$JFliM8Ja0VVGp76YozAQgOJBI2FN7Y8hHFeksGgvxUmyIorEf5MBm', 'N', SYSDATE, SYSDATE, 'N', SYSDATE, 'Y');

INSERT INTO AUTH_SCHEMA."APPLICATION" (ID, NAME, CREATED_AT, UPDATED_AT, DESCRIPTION, APP_ID, APP_SECRET, URL, WEB_CONTEXT, PORT, URI, IS_ENABLE) VALUES(AUTH_SCHEMA.SEQ_APPLICATION.NEXTVAL, 'MAIL SERVICE', SYSDATE, SYSDATE, 'A mail service API', 'MAIL_API', 'blablabla', 'http://localhost:8181', '/mail', 8181, 'http://localhost:8181/mail', 'Y');

INSERT INTO AUTH_SCHEMA."ROLE" (ID, NAME, CREATED_AT, UPDATED_AT, DESCRIPTION, APP_ID, IS_ENABLE) VALUES(AUTH_SCHEMA.SEQ_ROLE.NEXTVAL, 'ROLE_SEND', SYSDATE, SYSDATE, 'Role to send email', AUTH_SCHEMA.SEQ_APPLICATION.CURRVAL, 'Y');

INSERT INTO AUTH_SCHEMA."PRIVILEGE" (ID, NAME, CREATED_AT, UPDATED_AT, IS_ENABLE) VALUES(AUTH_SCHEMA.SEQ_PRIVILEGE.NEXTVAL, 'AUTHORITY_SENDER', SYSDATE, SYSDATE, AUTH_SCHEMA.SEQ_ROLE.CURRVAL , 'Y');

INSERT INTO AUTH_SCHEMA."ACCESS" (ID, PRIVILEGE_ID, ROLE_ID, USER_ID, CREATED_AT, UPDATED_AT) VALUES(AUTH_SCHEMA.SEQ_ACCESS.NEXTVAL, AUTH_SCHEMA.SEQ_PRIVILEGE.CURRVAL, AUTH_SCHEMA.SEQ_ROLE.CURRVAL, AUTH_SCHEMA.SEQ_USER.CURRVAL, SYSDATE, SYSDATE);
