CREATE SCHEMA IF NOT EXISTS "AUTH_SCHEMA";

DROP TABLE IF EXISTS AUTH_SCHEMA.USER;
DROP TABLE IF EXISTS AUTH_SCHEMA.APPLICATION;
DROP TABLE IF EXISTS AUTH_SCHEMA.ROLE;
DROP TABLE IF EXISTS AUTH_SCHEMA.PRIVILEGE;

CREATE TABLE IF NOT EXISTS AUTH_SCHEMA.USER (
    ID NUMBER(10) NOT NULL,
	NAME VARCHAR2(200) NOT NULL,
	LOGIN VARCHAR2(100) NOT NULL,
	PASSWORD VARCHAR2(200) NOT NULL,
	IS_BLOCKED CHAR(1) NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP NOT NULL,
	IS_PASS_EXPIRED CHAR(1) NOT NULL,
	PASS_EXPIRE_DATE DATE NOT NULL,
    IS_ENABLE CHAR(1) NOT NULL,
    CONSTRAINT USER_PK PRIMARY KEY (ID),
    CONSTRAINT USER_UN_LOGIN UNIQUE (LOGIN)
);

CREATE UNIQUE INDEX USER_LOGIN_IDX ON AUTH_SCHEMA.USER (LOGIN);
ALTER TABLE AUTH_SCHEMA."USER"    ADD CONSTRAINT USER_IS_BLOCKED CHECK ("IS_BLOCKED" IN ('Y','N'));
ALTER TABLE AUTH_SCHEMA."USER"    ADD CONSTRAINT USER_IS_PASS_EXPIRED CHECK ("IS_PASS_EXPIRED" IN ('Y','N'));
ALTER TABLE AUTH_SCHEMA."USER"    ADD CONSTRAINT USER_IS_ENABLE CHECK ("IS_ENABLE" IN ('Y','N'));

CREATE SEQUENCE IF NOT EXISTS AUTH_SCHEMA.SEQ_USER;
